version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest

  python:
    build:
      context: .
      dockerfile: python.Dockerfile

  ruby:
    build:
      context: .
      dockerfile: ruby.Dockerfile

  js:
    build:
      context: .
      dockerfile: js.Dockerfile

  haskell:
    build:
      context: .
      dockerfile: haskell.Dockerfile

  go:
    build:
      context: .
      dockerfile: go.Dockerfile

